### ISSUE TITLE
Supervisord ctl status shows lowercase program names

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#102]
`supervisord ctl status` shows the program names in all lower case.

`[program:MainServer]`

```
$ supervisord ctl status
mainserver                       RUNNING   pid 1317, uptime 0:01:00
```

https://github.com/ochinchina/supervisord/issues/94#issuecomment-411158586

**Comment by Siecje** [comment]
https://github.com/ochinchina/supervisord/blob/744436d1f634ca2b22683c7771149fc784b870b5/ctl.go#L81

**Comment by ochinchina** [comment]
@Siecje don't convert the program to lower case anymore

**Comment by Siecje** [comment]
Awesome @ochinchina !

This is fixed with https://github.com/ochinchina/supervisord/commit/4fcca4b496bd99b48a490d9b79ac2eca259c5800
