### ISSUE TITLE
supervisord ctl status should be ordered

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#103]
The output `supervisord ctl status` is different each time it is run. This makes it hard to use with `watch` when you are waiting to see if a process will start properly.

**Comment by ochinchina** [comment]
the program is sorted by its name in the "supervisord ctl status"

**Comment by Siecje** [comment]
Awesome! This has been fixed with https://github.com/ochinchina/supervisord/commit/d5ea22b602737fab88b062b76e92333c5adf3723.
