### ISSUE TITLE
The init status of process should be STARTING

### ISSUE THREAD

**Issue by virusdefender** [ochinchina/supervisord#106]
It seems the status of a new process is RUNNING, and it is STARTING in python-supervisor.

After `startsecs` the status can be switched.

> startsecs
> 
> The total number of seconds which the program needs to stay running after a startup to consider the start successful (moving the process from the STARTING state to the RUNNING state).

**Comment by ochinchina** [comment]
@virusdefender the issue is fixed, please try

**Comment by virusdefender** [comment]
Confirmed, thanks
