### ISSUE TITLE
`startretries` seems do not work

### ISSUE THREAD

**Issue by virusdefender** [ochinchina/supervisord#108]
```
[supervisord]
logfile = /dev/stdout
logfile_maxbytes = 0
nodaemon = true
autorestart=unexpected

[inet_http_server]
port = 127.0.0.1:9005

[supervisorctl]
serverurl = http://127.0.0.1:9005

[program:process]
command = /conf/run.sh
startsecs = 3
startretries = 3
```

run.sh
```
#! /bin/bash
sleep 1
exit 1
```

supervisor is always retrying

```
root@7da10350db50:/# /usr/local/bin/supervisord -c /conf/supervisord.conf
time="2018-09-17T11:46:51Z" level=info msg="create process:process"
time="2018-09-17T11:46:51Z" level=info msg="try to start program" program=process
time="2018-09-17T11:46:51Z" level=info msg="success to start program" program=process
time="2018-09-17T11:46:54Z" level=error msg="program stopped with error:exit status 1" program=process
time="2018-09-17T11:46:54Z" level=info msg="success to start program" program=process
time="2018-09-17T11:46:57Z" level=error msg="program stopped with error:exit status 1" program=process
time="2018-09-17T11:46:57Z" level=info msg="success to start program" program=process
time="2018-09-17T11:47:00Z" level=error msg="program stopped with error:exit status 1" program=process
time="2018-09-17T11:47:00Z" level=info msg="success to start program" program=process
time="2018-09-17T11:47:03Z" level=error msg="program stopped with error:exit status 1" program=process
time="2018-09-17T11:47:03Z" level=info msg="success to start program" program=process
time="2018-09-17T11:47:06Z" level=error msg="program stopped with error:exit status 1" program=process
```

I'm using the master version, compiled in docker

**Comment by ochinchina** [comment]
@virusdefender this issue is fixed and please test it. By the way startretries  is only valid within startsecs.

**Comment by haraldschilly** [comment]
@ochinchina we just updated to 0.5 in production and noticed, that somehow the semantics did change? we want to run job just once or never, and hence had `startretries = 0` in the config file. Previously, it attempted it once (sometimes successful) and never tried again. Now, it immediately says it retries too often. Line 3 and 4 in the log:

```
time="2018-09-24T07:23:51Z" level=info msg="try to start program" program=project_init_sh
time="2018-09-24T07:23:51Z" level=error msg="fail to start program because retry times is greater than 0" program=project_init_sh
```

I'm not sure if our previous config was wrong, or what should be the correct setting, though. It's just that I interpreted "retries = 0" that it attempts once and not again. I did read 026fb4b34c3fa1aa7e0ce2d817967c969c68c4c6 but I wasn't able to understand where exactly the difference is coming from (at the bottom, it looks like  it increments the counter after the first `>=` check … which is what I would do, too)

**Comment by ochinchina** [comment]
@haraldschilly sorry it is my fault to make such issue when fixing startretries  problem, now it is fixed. Please try it

**Comment by williamstein** [comment]
I work with @haraldschilly  on CoCalc.  With the latest change, supervisord completely hangs on startup, which is a huge bug for us that I can't figure out how to work around.  I'm going to try to fork your project back one commit and revert our Docker build to use that for now.

**Comment by ochinchina** [comment]
@williamstein I fixed a hangs and I don't know if this fixed hangs is yours, please try again.

If this fix can't solve your hangs, can you provide your configuration for me and I will test it.

**Comment by williamstein** [comment]
It still hangs completely.   Our current workaround for production is using the last binary we built of supervisord, since I wasn't even able to figure out how to build from an older commit and have that work (I don't know if this suggests a related upstream problem or what).  

> If this fix can't solve your hangs, can you provide your configuration for me and I will test it.

Create a CoCalc project at (https://cocalc.com), then click +New --> Terminal, and you'll get a command line terminal.  We run supervisord via:
```
# Run the GO version of Supervisord
exec /cocalc/bin/supervisord -c /cocalc/supervisor/supervisord.conf
```
Thus you can see in /cocalc/supervisord (just cd in the terminal) what the config is.  

Click the "help" button in the upper right and mention supervisord and I'll upgrade your project to have internet access etc., and then you can pull the sources from github, build (we have a build chain installed, I think), and test running our config there.   The init script that launches supervisord is /cocalc/init/init.sh

Anyway, let me know if you have any ideas or can fix this.  Otherwise, we'll have to switch back to the original Python supervisord, I guess, or something else entirely.

**Comment by ochinchina** [comment]
@williamstein I fixed your findings and you can retry it now.

**Comment by williamstein** [comment]
I'm happy to report that it now seems to work perfectly for us!  **THANKS!**

**Comment by faith2god** [comment]
startretries seems don't work
just like virusdefender's config, process is keeping STARTING state all the time

supervisor logs here
```
time="2019-08-08T16:43:12+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:12+08:00" level=error msg="fail to start program because retry times is greater than 3" program=process
time="2019-08-08T16:43:13+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:15+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:16+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:16+08:00" level=error msg="fail to start program because retry times is greater than 3" program=process
time="2019-08-08T16:43:17+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:18+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:19+08:00" level=info msg="fail to wait for program exit" program=process
time="2019-08-08T16:43:19+08:00" level=error msg="fail to start program because retry times is greater than 3" program=proces
```

supervisord version: release 0.6.3, go build source code and run in ubuntu 14.04

**Comment by faith2god** [comment]
@ochinchina pls check it， thanks a lot
