### ISSUE TITLE
supervisord ctl start does not return to prompt

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#109]
I am using supervisord to run dropbear without backgrounding.

It used to work for this commit. https://github.com/ochinchina/supervisord/commit/ac8038805e0e7bdf4c67d8fdd51ba791fa1f4970

Now the command does not return to the prompt.

`supervisord ctl start dropbear`

Here is the dropbear config.

```
[program:dropbear]
;   -w  Disallow root logins
;   -g  Disable password logins for root
;   -k  Disable remote port forwarding
;   -r  Specify host keys (of various types)
;   -R  Creates keys on-the-fly if they can't be found.  Including as a failsafe.
;   -F  Do not run as daemon
command=/path/to/dropbear -w -g -k -r /path/to/dropbear/dropbear_dss_host_key -r /path/to/dropbear/dropbear_rsa_host_key -r /path/to/dropbear/dropbear_ecdsa_host_key -R -F
user=root
autostart=false
autorestart=true
startretries=5
stdout_logfile=syslog
stderr_logfile=syslog
stopwaitsecs=60
stopsignal=TERM
```

**Comment by ochinchina** [comment]
@Siecje do you mean the command "supervisord ctl start dropbear" hangs up forever?

**Comment by Siecje** [comment]
Yes

**Comment by ochinchina** [comment]
@Siecje fixed, please try it

**Comment by Siecje** [comment]
Yes was fixed by https://github.com/ochinchina/supervisord/commit/e1b4d5cbda587dd34dc269ac49c97c409d319fef
