### ISSUE TITLE
An error causes supervisord to stop running

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#110]
While testing https://github.com/ochinchina/supervisord/issues/96 I noticed strange behaviour.

This was my script and config file.

cody.py
```Python
#!/usr/bin/python
import sys
print(sys.argv)
```

cody.conf
```
[program:cody]
command=/boot/dd/cody.py
    1 ; comment1
    2 ; comment 2
user=server
autostart=false 
startretries=5
stdout_logfile=syslog
stderr_logfile=syslog
exitcodes=0
autorestart=unexpected
```

Before starting `cody` `supervisord ctl status` works.
After `supervisord ctl start cody` `supervisord ctl status` does not work.

I see the output from the script in syslog but also an error message. I might be using `exitcodes` and `autorestart=unexpected` incorrectly, but I think it should just run once and then exit and supervisord should not restart it. http://supervisord.org/configuration.html?highlight=autorestart

```
Sep 28 15:11:42 box kern.debug cody[792]: ['/boot/dd/cody.py', '1', '2']
Sep 28 15:11:42 box kern.debug supervisord[792]: time="2018-09-28T15:11:42Z" level=error msg="fail to start program because retry times is greater than 5" program=cody
```

`supervisord` is no longer running.

Even if that error message is correct `supervisord` should stay running and `supervisord ctl status` should still work.

```shell
$ supervisord ctl status
$ echo $?
1
```

There is no output from `supervisord ctl status`.

If I try to start `cody` again I get an error.

```shell
$ supervisord ctl start cody
cody: failed [Post http://localhost:9001/RPC2: dial tcp 127.0.0.1:9001: connect: connection refused]
```

**Comment by ochinchina** [comment]
@Siecje fixed your issue, please try again

**Comment by ochinchina** [comment]
Disabled the "Grim reaper disabled, pid not 1" message. Please try it.

**Comment by Siecje** [comment]
Thanks! This is working great!
