### ISSUE TITLE
Default value for configFile

### ISSUE THREAD

**Issue by vmanyushin** [ochinchina/supervisord#113]
https://github.com/ochinchina/supervisord/blob/12317cc3f52150736cb032a1e4d2d07e5ace6608/config/config.go#L98

How about set default config file location (e.g. /etc/supervisord.conf) if it not passed from command line?

**Comment by ochinchina** [comment]
There is default configuration file which is `pwd`/supervisord.conf,

type Options struct {
	Configuration string `short:"c" long:"configuration" description:"the configuration file" default:"supervisord.conf"`
	Daemon        bool   `short:"d" long:"daemon" description:"run as daemon"`
	EnvFile       string `long:"env-file" description:"the environment file"`
}

**Comment by vmanyushin** [comment]
ok, i understand that i need to set WORKDIR to /usr/local/bin
