### ISSUE TITLE
inet_http_server

### ISSUE THREAD

**Issue by litliq** [ochinchina/supervisord#114]
i change supervisord.conf to  supervisord_test.conf
and set   "port=10.64.1.113:9001" 

start with "./supervisord -c supervisord_test.conf -d"

but exec "./supervisord ctl shutdown"  Error
Error Info: Post http://localhost:9001/RPC2

 The Configuration in Options is used Default "supervisord.conf"
So the func "getServerUrl" return the url "http://localhost:9001"

**Comment by ochinchina** [comment]
please add section supervisorctl to your supervisord_test.conf like below:
```
[supervisorctl]
serverurl=http://10.64.1.113:9002
```

and then execute shutdown like:

./supervisord -c supervisord_test.conf ctl shutdown
