### ISSUE TITLE
unix_http_server not working (using port instead with connection refused!)

### ISSUE THREAD

**Issue by mmmint** [ochinchina/supervisord#117]
Hi guys!
Awesome job you are doing with this porting..
Unfortunately I cannot manage to run it using `unix_http_server` directive. I seems to use `tcp_http_server` instead! Using `supervisord v.0.5`.

Here what I have so far...
`/etc/supervisord.conf`
```
[program:app]
user=root
numprocs=1
command=/usr/bin/app

[unix_http_server]
file = /tmp/supervisord.sock
chmod = 0700
username = dummy
password = dummy

[supervisorctl]
serverurl = unix:///tmp/supervisord.sock
username = dummy
password = dummy
```
<br>
Then daemonize supervisord...

`/usr/sbin/supervisord -c /etc/supervisord.conf -d`
<br>
When executing `/usr/sbin/supervisord ctl -v status` I get an error in verbose mode:

`Fail to send request to supervisord: Post http://localhost:9001/RPC2: dial tcp 127.0.0.1:9001: connect: connection refused`

**Comment by ochinchina** [comment]
I will test your case to find root cause

**Comment by ochinchina** [comment]
@mmmint I tested your bug fix and find the root cause, please get the latest source code to test if it works.

**Comment by mmmint** [comment]
Still after compiling latest version and executing...

`Fail to send request to supervisord: Post http://localhost:9001/RPC2: dial tcp 127.0.0.1:9001: connect: connection refused`

**Comment by mmmint** [comment]
Even when using `inet_http_server` and using another port than 9001, it fails with the same above stated error message!

**Comment by ochinchina** [comment]
please send request to supervisord by following commands:

```
/usr/sbin/supervisord -c /etc/supervisord.conf ctl -v status
```

**Comment by mmmint** [comment]
Already did! Like I said:
- `unix_http_server` directive is not working at all, failing with the above stated error message.
- `inet_http_server` directive does only work when using port 9001. When another port is used it does fail exiting with the same above stated error message.

**Comment by mmmint** [comment]
Already did, but saddly it's still not working! Here a summary:
- `unix_http_server` directive is not working at all, failing with the above stated error message.
- `inet_http_server` directive does ONLY work when using port 9001. When another port is used it does fail exiting with the same above stated error message.

**Comment by ochinchina** [comment]
I try to reproduce your issue in my Linux environment as below:

#### Step 1: edit the /usr/bin/app file, change its mode to executable and test if is works

```
$ cat /usr/bin/app
#!/bin/bash

echo "start the stdin test"
i=1
while true; do
      echo "this is a test $i of $1"
      i=$(($i+1))
      sleep 1
      if [ $i -gt 200 ]; then
          echo "exit"
          exit 1
      fi
done

$ sudo chmod +x /usr/bin/app
$ /usr/bin/app
start the stdin test
this is a test 1 of
this is a test 2 of
this is a test 3 of
^C
```
#### Step 2: edit the /etc/supervisord.conf and set its content as yours

```
$ cat /etc/supervisord.conf
[program:app]
user=root
numprocs=1
command=/usr/bin/app

[unix_http_server]
file = /tmp/supervisord.sock
chmod = 0700
username = dummy
password = dummy

[supervisorctl]
serverurl = unix:///tmp/supervisord.sock
username = dummy
password = dummy
```

#### Step 3: test if /usr/sbin/supervisord works

```
$ /usr/sbin/supervisord -h
Usage:
  supervisord [OPTIONS] <ctl | init | version>

Application Options:
  -c, --configuration= the configuration file (default: supervisord.conf)
  -d, --daemon         run as daemon
      --env-file=      the environment file

Help Options:
  -h, --help           Show this help message

Available commands:
  ctl      Control a running daemon
  init     initialize a template
  version  show the version of supervisor
```

#### Step 4: start the supervisord with configuration file /etc/supervisord.conf 

```
$ /usr/sbin/supervisord -c /etc/supervisord.conf -d
```

#### Step 5: check program status (fail to start the program /usr/bin/app )

```
$  /usr/sbin/supervisord -c /etc/supervisord.conf ctl status -v
app                              FATAL     1970-01-01 00:00:00 +0000 UTC
```

#### Step 6: shutdown the supervisord

```
$ /usr/sbin/supervisord -c /etc/supervisord.conf ctl shutdown 
```

#### Step 7: add log for the supervisord by changing the /etc/supervisord.conf
```
$ cat 
[supervisord]
logfile=/tmp/supervisord.log
loglevel=debug

[program:app]
user=root
numprocs=1
command=/usr/bin/app

[unix_http_server]
file = /tmp/supervisord.sock
chmod = 0700
username = dummy
password = dummy

[supervisorctl]
serverurl = unix:///tmp/supervisord.sock
username = dummy
password = dummy

```

#### Step 8: restart supervisord again

```
$ /usr/sbin/supervisord -c /etc/supervisord.conf -d

```

#### Step 9: check the supervisord log /tmp/supervisord.log.0

```
$ cat /tmp/supervisord.log.0
time="2018-12-15T03:18:23Z" level=info msg="create process:app"
time="2018-12-15T03:18:23Z" level=info msg="try to start program" program=app
time="2018-12-15T03:18:23Z" level=debug msg="require authentication"
time="2018-12-15T03:18:23Z" level=debug msg="require authentication"
time="2018-12-15T03:18:23Z" level=debug msg="require authentication"
time="2018-12-15T03:18:23Z" level=debug msg="require authentication"
time="2018-12-15T03:18:23Z" level=error msg="fail to start program with error:fork/exec /usr/bin/app: operation not permitted" program=app
time="2018-12-15T03:18:23Z" level=error msg="fail to start program with error:fork/exec /usr/bin/app: operation not permitted" program=app
time="2018-12-15T03:18:23Z" level=error msg="fail to start program with error:fork/exec /usr/bin/app: operation not permitted" program=app
time="2018-12-15T03:18:23Z" level=error msg="fail to start program with error:fork/exec /usr/bin/app: operation not permitted" program=app
time="2018-12-15T03:18:23Z" level=error msg="fail to start program because retry times is greater than 3" program=app
time="2018-12-15T03:18:23Z" level=info msg="Don't start the stopped program because its autorestart flag is false" program=app
```
#### Step 10: shutdown the supervisord again

```
$ /usr/sbin/supervisord -c /etc/supervisord.conf ctl shutdown
```

#### Step 11: remove the user parameter for the application

```
$ cat /etc/supervisord.conf
[supervisord]
logfile=/tmp/supervisord.log
loglevel=debug

[program:app]
#user=root
numprocs=1
command=/usr/bin/app

[unix_http_server]
file = /tmp/supervisord.sock
chmod = 0700
username = dummy
password = dummy

[supervisorctl]
serverurl = unix:///tmp/supervisord.sock
username = dummy
password = dummy
```

#### Step 12:  remove log file /tmp/supervisord.log.0 and restart the supervisord
```
$ rm -rf 
$  /usr/sbin/supervisord -c /etc/supervisord.conf -d
```

#### Step 13: check the application status again
```
$ /usr/sbin/supervisord -c /etc/supervisord.conf ctl status
app                              RUNNING   pid 8511, uptime 0:00:12
```

#### Step 14: check the /tmp/supervisord.log.0

```
$ cat /tmp/supervisord.log.0
time="2018-12-15T03:24:44Z" level=info msg="create process:app"
time="2018-12-15T03:24:44Z" level=info msg="try to start program" program=app
time="2018-12-15T03:24:44Z" level=debug msg="require authentication"
time="2018-12-15T03:24:44Z" level=debug msg="wait program exit" program=app
time="2018-12-15T03:24:44Z" level=debug msg="require authentication"
time="2018-12-15T03:24:44Z" level=debug msg="require authentication"
time="2018-12-15T03:24:44Z" level=debug msg="require authentication"
time="2018-12-15T03:24:45Z" level=info msg="success to start program" program=app
time="2018-12-15T03:24:56Z" level=debug msg="Auth with normal password"
```

if you can repeat above steps to check what's wrong with your application? especially check the supervisord log file /tmp/supervisord.log.0

**Comment by Atoms** [comment]
i also had struggle with this, but i can confirm adding 
```
[supervisorctl]
serverurl = unix:///tmp/supervisord.sock
```
to config file all works as expected. Problem is lack of documentation or sample config file.

actually there is sample in `config_template.go` but all section documentation is missing anyway, so i would say documentation is needed to extend with more samples probably.

P.S. good job making this (python supervisor are unable to release python3 supported version so had to look other way)

**Comment by mmmint** [comment]
Thanks! Today did exactly the same as last day, but with the latest version from today. Result = all is working now!

Cool guys. Appreciate.
Regards,
Marc
