### ISSUE TITLE
supervisord ctl status result different

### ISSUE THREAD

**Issue by litliq** [ochinchina/supervisord#119]
[root@localhost Test]#./supervisord ctl status
CWBankOcrServer                  RUNNING   pid 163977, uptime 0:00:29
CWDriverCardOcrServer            RUNNING   pid 163971, uptime 0:00:29
CWFaceServer                     RUNNING   pid 163978, uptime 0:00:29
CWFaceSwapServer                 RUNNING   pid 163972, uptime 0:00:29
CWLipReadingServer               RUNNING   pid 163975, uptime 0:00:29
CWOcrServer                      RUNNING   pid 163976, uptime 0:00:29
appserver                        RUNNING   pid 163974, uptime 0:00:29

[root@localhost Test]# ./supervisord ctl status
CWDriverCardOcrServer            RUNNING   pid 163971, uptime 0:00:29
CWFaceServer                     RUNNING   pid 163978, uptime 0:00:29
CWOcrServer                      RUNNING   pid 163976, uptime 0:00:29
appserver                        RUNNING   pid 163974, uptime 0:00:29

the result is different when i exec ./supervisord ctl status
some processes are not found sometimes

**Comment by litliq** [comment]
modify like this:

func (pm *ProcessManager) ForEachProcess(procFunc func(p *Process)) {
	log.Info("StopAllProcesses start")
	pm.lock.Lock()
	defer pm.lock.Unlock()

	procs := pm.getAllProcess()
	log.Info("StopAllProcesses proc num: ", len(procs))
	done := make(chan struct{}, 1048576)

	for _, proc := range procs {
		time.Sleep(time.Millisecond)
		go forOneProcess(proc, procFunc, done)
	}

	for range procs {
		<-done
	}
}

**Comment by ochinchina** [comment]
you issue is raised because the method "ForEachProcess" is changed to Async mode. To fix this issue, I add a new method named "AsyncForEachProcess" to start/stop programs in async.

Please get the latest code to try if it is fixed.

**Comment by litliq** [comment]
Thanks

**Comment by litliq** [comment]
And i changed the function:

func (pm *ProcessManager) StopAllProcesses() {
	// Lit 19.01.02 
	finishedProcCh := make(chan *Process)
	n := pm.AsyncForEachProcess(func(proc *Process) {
		proc.Stop(true)
	}, finishedProcCh)

	for i := 0; i < n; i++ {
		proc, ok := <-finishedProcCh
		if ok {
			log.Info(proc.GetName(), " stopped")
		}
	}

/*	pm.ForEachProcess(func(proc *Process) {
		proc.Stop(true)
	})*/
}
