### ISSUE TITLE
supervisord ctl reload hangs supervisord

### ISSUE THREAD

**Issue by Atoms** [ochinchina/supervisord#120]
Installed supervisord 0.5 version from releases.
config as follows:
```
[unix_http_server]
file=/run/supervisord.sock

[supervisorctl]
serverurl = unix:///run/supervisord.sock

[supervisord]
logfile=/var/log/supervisord/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=debug
pidfile=/run/supervisord.pid

[include]
files=/etc/supervisord.d/*.conf
```

When i add new programm in `/etc/supervisord.d/app.conf` and do `supervisord ctl -c /etc/supervisord.conf reload` it is reloaded, but socket is lost and no commands from ctl is accepted anymore, getting message:
```
# supervisord -c /etc/supervisord.conf ctl status
Fail to connect unix socket path: unix:///run/supervisord.sock
```
and then there is no possibilities to stop it as it's not listening on socket anymore. 
tried to check logs and launch without daemon mode to see what happens, but there is nothing really happening, output of log after executing 2 commands status and reload:
```
DEBU[2018-12-28T15:28:22Z] no auth required                             
INFO[2018-12-28T15:28:22Z] start to reload config                           
```

**Comment by ochinchina** [comment]
fixed this issue and please get the latest code to test

**Comment by Atoms** [comment]
Issue fixed within master thanks
