### ISSUE TITLE
supervisord default config location

### ISSUE THREAD

**Issue by Atoms** [ochinchina/supervisord#121]
Have no clue if in master it's changed, but in 0.5 supervisord cannot save config path to use later for `ctl` 

if i launch supervisord with command:
```
 /usr/bin/supervisord -c /etc/supervisord.conf
```
then command `supervisord ctl ...` should reuse that configuration path so not to every command we should append config path for it to work.

In my opinion if i don't provide -c parameter on cli it should reuse config file with which it is loaded, if -c is provided then ignore this config file.

**Comment by ochinchina** [comment]
change the code to follow the supervisord configuration file location rule:

The Supervisor configuration file is conventionally named supervisord.conf. It is used by both supervisord and supervisorctl. If either application is started without the -c option (the option which is used to tell the application the configuration filename explicitly), the application will look for a file named supervisord.conf within the following locations, in the specified order. It will use the first file it finds.
```
1. $CWD/supervisord.conf
2. $CWD/etc/supervisord.conf
3. /etc/supervisord.conf
4. /etc/supervisor/supervisord.conf (since Supervisor 3.3.0)
5. ../etc/supervisord.conf (Relative to the executable)
6. ../supervisord.conf (Relative to the executable)
```

**Comment by Atoms** [comment]
Thanks this works as expected now :) can you mention issue number in commit so it gets linked to issue for better tracking :) So closing this now
