### ISSUE TITLE
log Console

### ISSUE THREAD

**Issue by litliq** [ochinchina/supervisord#123]
通过守护进程模式启动，控制台无法打印log
- /dev/stdout, write log to stdout
- /dev/stderr, write log to stderr
这两种方式都不行，只能通过文件方式保存到本地，但是不直观
现在既想log保存到本地，又想打印到控制台，请问有方法吗？

**Comment by ochinchina** [comment]
Please set the log file to /dev/stdout to print the log to console. If you want to print the log to both file and console, please set the log file as:
```
stdout_logfile = my_app.log, /dev/stdout
```

because now this supervisord supports multiple log files which is separated with comma ","

**Comment by gerroon** [comment]
How can I do this in Windows given no /dev/stdout exists?
