### ISSUE TITLE
Did someone get this to work in Alpine?

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [ochinchina/supervisord#132]
When i try to run supervisord in an alpine image, i get the error "not found".

Of course i made sure that i have all the necessary rights on the binary and the folder it is in, same for the config file.

i am starting it like this
CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

digging a bit deeper with "sh -xe" i can find out the following

```
line 1: can't create JE@p@8: Permission denied + ' ELF'
line 1: ELF: not found
```

I feel bad not knowing what ELF is, but searching for it didn't help me figure out what that should be. Anyone any idea?

**Comment by ochinchina** [comment]
Actually the released supervisor binary is compiled under alpine Linux, so it is a little bit strange the supervisord can't be started in the Alpine Linux.

To make sure what's wrong with your environment, we need to know:

- What is your alpine Linux version?
- Your alpine Linux is 64-bit? or 32-bit?

**Comment by ThomasSchoenbeck** [comment]
alpine version is 3.9
```sh
~ $ uname -a
Linux grafana-alpine-57-5zbkr 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 
```

build from scratch like this

```Dockerfile
FROM scratch

ADD rootfs.tar.xz /

CMD ["/bin/sh"]
```

**Comment by ochinchina** [comment]
@ThomasSchoenbeck link the supervisord with static libary instead of dynamic library, now it should be work under alpine 3.9 even though its libc library is different from ubuntu's. Please try it

**Comment by ThomasSchoenbeck** [comment]
Hi there,

yes it works. Thank you so much for the updated binary.
