### ISSUE TITLE
v6.0.3 release: the result of  supervsiord ctl status  is unnormal

### ISSUE THREAD

**Issue by faith2god** [ochinchina/supervisord#134]

**Comment by faith2god** [comment]
`#supervisord ctl status
processname:processname**status** `

Q1: programname doule, differ with version before
Q2: programname jointed with status code
eg: sheep(program)
sheep:sheepRUNNING 2019-04-15 16:57:08.584781797 +0700 ICT m=+1552894.619871953
 
env:
v6.0.3 source code, compiled by myself
linux

**Comment by ochinchina** [comment]
Before the program name, the group name is added. So a program is displayed with name "group:program" format.  If no group name is configured in the supervisor configration file, the group name will be the program name.

And we can disable the "group" name when displaying the program by:

- optional parameter, such as "--no-group-name", so the status command looks like:

# supervisord ctl status program --no-group-name

or
- Environment varaible, such as NO_GROUP_NAME, so we can disable the group name display by setting the NO_GROUP__NAME=yes

# export NO_GROUP__NAME=yes
# supervisord ctl status program

**Comment by ochinchina** [comment]
@faith2god By default, no group will be displayed now. And if want to display group name before program name, set the environment variable "SUPERVISOR_GROUP_DISPLAY" to "true"

**Comment by faith2god** [comment]
ok, I'll try, thanks a lot. you're very sweet

**Comment by l-duan** [comment]
did you fix this issue? the release version have not update yet.
