### ISSUE TITLE
Windows Error: reaper.go:23:22: undefined: syscall.SIGCHLD

### ISSUE THREAD

**Issue by BenDerPan** [ochinchina/supervisord#135]
# Try build on windows, go build error:
...\pkg\mod\github.com\ochinchina\go-reaper@v0.0.0-20181016012355-6b11389e79fc\reaper.go:23:22: undefined: syscall.SIGCHLD
...\pkg\mod\github.com\ochinchina\go-reaper@v0.0.0-20181016012355-6b11389e79fc\reaper.go:62:16: undefined: syscall.Wait4

**Comment by ochinchina** [comment]
I fixed this issue, please try it

**Comment by BenDerPan** [comment]
@ochinchina  yes, it works now, thanks :), close this now.

**Comment by navono** [comment]
Stil get the same error when install use:
> go get -u -v github.com/ochinchina/supervisord
