### ISSUE TITLE
no command supervisord restart program_name

### ISSUE THREAD

**Issue by fwhezfwhez** [ochinchina/supervisord#137]
I remember in python supervisord, It's using `supervisorctl restart program_name`.
But go version no such command.

How to restart my program when I have some updatings.
I'm expecting `supervsord ctl restart program_name`

or what replaces it,

I'm confused of supervisord ctl reload.

can I  exec `supervisord ctl reload program_name` to restart only a certain program?
I'm afraid all program will be reload when my purpose is only restart one of it.

3q.

**Comment by Siecje** [comment]
`restart` is listed here for the Python version. http://supervisord.org/running.html#supervisorctl-actions

**Comment by ochinchina** [comment]
@fwhezfwhez the restart command is added

**Comment by fwhezfwhez** [comment]
@ochinchina can it run in go versions lower than go 1.2?
I pull the latest version of supervisord@master, when `go build` get an error
`supervisord/config not found in any of GOPATH`, I guess current master only runable in go 1.2.

to fix this ,I find not only `supervisord/config` ,but 
```
	"supervisord/config"
	"supervisord/types"
	"supervisord/xmlrpcclient"
	"supervisord/events"
	"supervisord/events"
	"supervisord/faults"
	"supervisord/logger"
	"supervisord/util"
```
these also unacessable.

to execute `go build`, main.go might import unaccessable path `supervisord/config` and cause this problem.

I'm wandering whether I can modify `supervisor/x`  to `github.com/ochinchina/supervisord/x`.
By achieving this, program can run well in all go version.

I've pull a request to fix if you think ok.
I can't ensure whether one of your ci script will fail if I change `supervisor/x`  to `github.com/ochinchina/supervisord/x`, you might judge yourself.
