### ISSUE TITLE
Can't run process as a specific user

### ISSUE THREAD

**Issue by ochinchina** [ochinchina/supervisord#14]
Currently, the processes started by the supervisord can only be ran under the same user as the supervisord.

**Comment by ochinchina** [comment]
fix this issue and the process can be running under specific user

**Comment by tjohnston-cd** [comment]
Is this fixed? I'm debugging an issue right now.. if I uncomment a line that says `user=<username>` in one of my services, I get the crash shown in https://github.com/ochinchina/supervisord/issues/254

I know the user exists (I can `id <username>` and get back a correct result). The same service starts up correctly without the `user=<username>` line added in.

**Comment by tjohnston-cd** [comment]
> Is this fixed? I'm debugging an issue right now.. if I uncomment a line that says `user=<username>` in one of my services, I get the crash shown in #254
> 
> I know the user exists (I can `id <username>` and get back a correct result). The same service starts up correctly without the `user=<username>` line added in.

Ah, never mind. False alarm! Just needed to compile our own build and this is now working.
Thanks for this project!
