### ISSUE TITLE
no root account

### ISSUE THREAD

**Issue by litliq** [ochinchina/supervisord#147]
FATA[2019-05-23T14:28:09+08:00] Unable to run                                 err="open /dev/stdout: permission denied"

使用一个非root账号，没有/dev权限，启动时"Deamonize"函数会报错
context := daemon.Context{LogFileName: "/dev/stdout"}
child, err := context.Reborn()
不知道是否能解决这个问题，又不影响log的控制台打印

**Comment by litliq** [comment]
child, err := context.Reborn()
	if err != nil {
		log.WithFields(log.Fields{"err": err}).Error("Unable to show log on console")
//		log.WithFields(log.Fields{"err": err}).Fatal("Unable to run")
	}
	if child != nil {
		return
	} else {
		context_temp := new(daemon.Context)
		child, err = context_temp.Reborn()
		if err != nil {
			log.WithFields(log.Fields{"err": err}).Error("Unable to run Deamon")
		}
		if child != nil {
			return
		}
	}

**Comment by ochinchina** [comment]
@litliq it is solved, please try it

**Comment by litliq** [comment]
It works!
Thanks!!!
