### ISSUE TITLE
directory setting in program not work

### ISSUE THREAD

**Issue by anotherGoogleFan** [ochinchina/supervisord#149]
It works fine if the setting is like this:
```
[program:test]
command=/data/test/test
```
But it does not work if the setting is like this:
```
[program:test]
directory=/data/test
command=./test
```
the error is: cannot find command: ./test。
It seems like that the "directory" setting not works.
Did I do anything wrong?

**Comment by ochinchina** [comment]
@anotherGoogleFan, The "directory" parameter means after the program is started, its current path will become to the path specified in "directory" parameter. The command will not be searched under "directory" if the command path is not absolute.

**Comment by anotherGoogleFan** [comment]
@ochinchina OK, I see. Thanks a lot.
