### ISSUE TITLE
[NFR] timer/cron block

### ISSUE THREAD

**Issue by lajosbencz** [ochinchina/supervisord#161]
It would be really handy to be able to declare timer/cron blocks to run scheduled commands.
The timer block would reference a list program blocks, just as the group block does.

Example of proposed config:

```
[program:send-reminders]
command=send_reminders.sh
autostart=false
autorestart=false

[timer:daily]
programs=send-reminders
calendar= *-*-* 06:00:00
```

The calendar key would have the same syntax as systemd's OnCalendar
EDIT: Or maybe this package could be used, with their syntax definition: https://godoc.org/github.com/robfig/cron

Thank You for considering!

**Comment by ochinchina** [comment]
@lajosbencz Can we add new parameters into the "program:xxx" section to implement your requirement? For example, we add "cron" parameter in the "program:xxx" in section to indicate this program is a cron program. After adding the "cron" parameter in the "program:xxx", your example will become to:
```ini
[program:send-reminders]
command=send_reminders.sh
autostart=false
autorestart=false
cron=* * * 06:00:00
```

**Comment by ochinchina** [comment]
@lajosbencz add parameter "cron" in section "program:xxx" for your request. The syntax of cron expression is defined in https://godoc.org/github.com/robfig/cron as your suggested

**Comment by lajosbencz** [comment]
Awesome! Thank you very much!
I'll give it a try in a few days and let you know if anything pops up!
