### ISSUE TITLE
set program config default value globally

### ISSUE THREAD

**Issue by edolphin-ydf** [ochinchina/supervisord#165]
Is it possible to set program config default value globally ?
 In my usecase, I will set some option in program section like autorestart, redirect_stderr... for every program. And there are many duplicated config. It would be nice to be able to set this option in a global section eg: supervisord section. 

Below is something i would like.
```
[inet_http_server]
port=127.0.0.1:9001

[supervisord]
logfile = /tmp/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=10
loglevel = info
pidfile = /tmp/supervisord.pid

# below 3 option are not supported in supervisord, but in program is ok now.
autorestart = false
redirect_stderr = true
restart_when_binary_changed = true

[program:mlconfigcenter]
command = commandA
directory = dirA
stdout_logfile = /tmp/mlconfigcenter.log

[program:mlgw]
command = commandB
stdout_logfile =dirB
....
```

**Comment by ochinchina** [comment]
it is good idea to set the default values for programs. I will consider to add it

**Comment by ochinchina** [comment]
@edolphin-ydf do you have any idea on what parameters can be put as global parameters?

**Comment by edolphin-ydf** [comment]
@ochinchina Any parameter is ok.  Here are some that i prefered and maybe it's not properply.

autostart
startsecs
startretries
autorestart
exitcodes
stopsignal
stopwaitsecs
stdout_logfile_maxbytes
stdout_logfile_backups
redirect_stderr
stderr_logfile_maxbytes
stderr_logfile_backups
environment
priority
user
directory
restart_when_binary_changed

**Comment by ochinchina** [comment]
@edolphin-ydf I want to put the default parameters to the section named "program-default", is this name ok? or you can givev me a suggestion name.

**Comment by edolphin-ydf** [comment]
Of course it's ok and it's better than what i'v described in the question. A standlone section makes it more clearer.
