### ISSUE TITLE
supervisord tries killing a stopped program

### ISSUE THREAD

**Issue by sandeepkalra** [ochinchina/supervisord#166]
I have an entry that is not planned on being restarted. It is there to create postgresdb

[program:initdb]
command=pg_ctl -D /postgresql/data -l /log/postgres/server.log initdb
user=postgres
autostart=false

On killing the docker, i see this in logs:
time="2019-12-07T03:59:14Z" level=info msg="stop the program" program=initdb
time="2019-12-07T03:59:14Z" level=info msg="force to kill the program" program=initdb

If this was not marked for autostart,  why is it being stopped?

**Comment by ochinchina** [comment]
@sandeepkalra , the initdb is not started but the supervisor try to kill it when the supervisor stops. Is my understanding correct>

**Comment by sandeepkalra** [comment]
You can have a simple helloworld program here (instead of initdb). The idea is to do things just once, and get killed. The supervisord must only stop something that is "running" and not try to stop something that has stopped.
In my case initdb did initialization of a database directory and then the program ended. The autostart was set to false so that it is not restarted by supervisord.

**Comment by ochinchina** [comment]
@sandeepkalra I fixed this issue, please try again

**Comment by sandeepkalra** [comment]
Thanks, I could not test because of issue #178 that I just opened. The logger library is missing from github!

**Comment by sandeepkalra** [comment]
Working now!
