### ISSUE TITLE
NewLogtail(s).CreateHandler() not found

### ISSUE THREAD

**Issue by happyEgg** [ochinchina/supervisord#168]
latest
github.com/ochinchina/supervisord/xmlrpc.go:95:21: undefined: NewLogtail

**Comment by ochinchina** [comment]
@happyEgg sorry missing a new .go file and I added it into repo now. Please try again

**Comment by stavgayer** [comment]
@ochinchina Still broken
`./logtail.go:52:27: undefined: logger.NewChanLogger

./logtail.go:53:28: compositeLogger.AddLogger undefined (type *logger.CompositeLogger has no field or method AddLogger)

./logtail.go:65:28: compositeLogger.RemoveLogger undefined (type *logger.CompositeLogger has no field or method RemoveLogger)`

**Comment by ahdai0718** [comment]
> @ochinchina Still broken
> `./logtail.go:52:27: undefined: logger.NewChanLogger
> 
> ./logtail.go:53:28: compositeLogger.AddLogger undefined (type *logger.CompositeLogger has no field or method AddLogger)
> 
> ./logtail.go:65:28: compositeLogger.RemoveLogger undefined (type *logger.CompositeLogger has no field or method RemoveLogger)`

Same here.
