### ISSUE TITLE
supervisord ctl stop server invalid

### ISSUE THREAD

**Issue by happyEgg** [ochinchina/supervisord#169]
my supervisor.conf
[inet_http_server]
port = :9001

[program:server]
directory = /work/src
command = ./run.sh
stdout_logfile=/work/src/logs/stdout.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
startsecs=3
startretries=3

当我执行 supervisord ctl stop server 命令后，此命令会一直阻塞，无法结束。

run.sh
#!/bin/bash
pgrep server | xargs kill -9
\# shellcheck disable=SC2164
cd /work/src
nohup ./server -f xxx &

sysctl -w net.ipv4.ip_forward=1

**Comment by ochinchina** [comment]
@happyEgg seems your run.sh script runs in background mode. Please don't run it in the background. Could you please change your run.sh script to:
```shell
#!/bin/bash

pgrep server | xargs kill -9
cd /work/src
./server -f xxx
```

**Comment by happyEgg** [comment]
I'm try it,tks
