### ISSUE TITLE
v0.6.3 need the permission of /dev/stdout?

### ISSUE THREAD

**Issue by faith2god** [ochinchina/supervisord#174]
unable to run supervisord by unroot user
error info:

`FATA[2019-12-31T16:32:44+07:00] Unable to run                                 err="open /dev/stdout: permission denied"`

**Comment by iNevd** [comment]
change code https://github.com/ochinchina/supervisord/blob/54c06798f129fb5f10257d95ab2030b97fe59bef/daemonize.go#L11
to
	`context := daemon.Context{}`

then, rebuild it.

ref: https://stackoverflow.com/questions/16747449/runuser-permission-denied-on-dev-stdout

**Comment by faith2god** [comment]
ok, thanks a lot. and v0.6.5 has fixed it
