### ISSUE TITLE
Stopping programs is broken

### ISSUE THREAD

**Issue by rse** [ochinchina/supervisord#179]
With the commit https://github.com/ochinchina/supervisord/commit/044359273707e3005934f33d68b044bcc31e6c74 I now see that the stopping of programs no longer works. When taking the latest "master" but with this small change reverted, stopping of programs works just fine again. If time permits I'll dig deeper, but I at least want to let you know that the current master HEAD is broken because of this change. As you know your codebase better, perhaps you can check this part yourself, too.

It still might not help very much, but my configuration is:
```
;;
;;  supervisord.ini -- SupervisorD Server Configuration
;;

[supervisord]                   
logfile                 = /dev/stdout
loglevel                = info

[supervisorctl]                                       
serverurl               = unix:///app/var/supervisor.sock               
                                                      
[unix_http_server]                                    
file                    = /app/var/supervisord.sock                            

[program:start]
priority                = 10
command                 = /app/sbin/rc start
user                    = root
autostart               = true
autorestart             = false
startretries            = 0
stopsignal              = TERM KILL
stopwaitsecs            = 10
stdout_logfile          = /dev/stdout
stderr_logfile          = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:postgresql-tmp]
priority                = 10
command                 = /app/sbin/rc postgresql tmp
user                    = root
autostart               = false
autorestart             = true
startretries            = 1
stopsignal              = TERM QUIT KILL
stopwaitsecs            = 10
stdout_logfile          = /dev/stdout
stderr_logfile          = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:postgresql-std]
priority                = 10
command                 = /app/sbin/rc postgresql std
user                    = root
autostart               = false
autorestart             = true
startretries            = 1
stopsignal              = TERM QUIT KILL
stopwaitsecs            = 10
stdout_logfile          = /dev/stdout
stderr_logfile          = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
```

And a `/app/sbin/supervisord -c /app/etc/supervisord.ini ctl -s unix:/app/var/supervisord.sock stop postgresql-std` command is no longer able to stop the `postgresql-std` program. With the mentioned commit reverted, this setup works just fine again and both `postgresql-tmp` and `postgresql-std` can be started and stopped just fine

(BTW, this is just a PostgreSQL docker container context where database init procedures are running with the help of a temporary PostgreSQL process and the regular RDBMS is started with the standard PostgreSQL process and all this is orchestrated through SupervisorD).

**Comment by ochinchina** [comment]
@rse I will check it soon

**Comment by ochinchina** [comment]
@rse I fixed this issue, please test it

**Comment by rse** [comment]
I've tested the new SupervisorD 0.6.7 version and this problem is now fixed. Thanks.
