### ISSUE TITLE
unix_http_server and inet_http_server can not co-exists.

### ISSUE THREAD

**Issue by wxiaoguang** [ochinchina/supervisord#183]
unix_http_server and inet_http_server can not co-exists.

If both of them exist, one may fail without any message.

Code: https://github.com/ochinchina/supervisord/blob/407af88ebf4f9a01617352746b21a312fc044b28/xmlrpc.go#L86

```
	if p.started {
		return
	}
	p.started = true
```
This code is executed in two go-routines, sometimes both start, sometimes only on can start.

In the generated init template, both section exist, it take me many hours to debug why ctl can not connect to the server.

**Comment by sandeepkalra** [comment]
Hi @wxiaoguang, I could not reproduce, but based on your code directions tried to fix it.
Is it possible for you to test again from this branch: 
https://github.com/sandeepkalra/supervisord/tree/fix_183

**Comment by wxiaoguang** [comment]
I don' think that PR helps.

The root problem is here:

https://github.com/ochinchina/supervisord/blob/407af88ebf4f9a01617352746b21a312fc044b28/supervisor.go#L465

```
go s.xmlRPC.StartInetHttpServer(httpServerConfig.GetString("username", ""), httpServerConfig.GetString("password", ""), addr, s)

go s.xmlRPC.StartUnixHttpServer(httpServerConfig.GetString("username", ""), httpServerConfig.GetString("password", ""), sockFile, s)
```

then `StartInetHttpServer` and `StartUnixHttpServer` both call `startHttpServer`. If one of the go routine executes faster and set `started = true`, the other won't have a chance to start.

The fix can be like this:

```
func (p *XmlRPC) StartUnixHttpServer(user string, password string, listenAddr string, s *Supervisor) {
	os.Remove(listenAddr)
	if p.startedUnixHttpServer {
		return
	}
	p.startedUnixHttpServer = true
	p.startHttpServer(user, password, "unix", listenAddr, s)
}

func (p *XmlRPC) StartInetHttpServer(user string, password string, listenAddr string, s *Supervisor) {
	if p.startedInetHttpServer {
		return
	}
	p.startedInetHttpServer = true
	p.startHttpServer(user, password, "tcp", listenAddr, s)
}


// remove the old p.started

```

**Comment by sandeepkalra** [comment]
@wxiaoguang Your suggested changes can also produce race-conditions. The check "if  p.startedInetHttpServer " and "p.startedUnixHttpServer " must be "atomic", and that is what I was doing with my changes.

**Comment by wxiaoguang** [comment]
@sandeepkalra 

No, I do not need them co-exist. But your default template makes them co-exist and I didn't modify these default settings, which lead to the problem. This behavior may mislead others. Default template:  https://github.com/ochinchina/supervisord/blob/407af88ebf4f9a01617352746b21a312fc044b28/config_template.go#L8 . I think there may be some users need them co-exist ...


About the race-condition, it seldom occurs because the `startHttpServer` is only called by `Reload` at https://github.com/ochinchina/supervisord/blob/407af88ebf4f9a01617352746b21a312fc044b28/supervisor.go#L398  . The fix is good, while in real world no one will be affected by the race-condition.

**Comment by sandeepkalra** [comment]
If you were no requesting a co-existence of both INET and HTTP server then my fix should work. 

I converted p.started to atomic *uint32, and now it only allows one to executed by one thread and others will be denied. 

The suggestions you made are still not atomic, and rather including 2 sets of different variables to track each thread will make it more likely to get into the race condition. 

I agree that the load/reload of conf can be used to strip one of the servers and that proactive decision disallows the condition to appear, but the server code isn't prepared for it with this proactive decision.

I will leave "Steven Ou" to decide on the fix that I did as he is the main owner of this repo.

**Comment by wxiaoguang** [comment]
I agree to make the variable atomic. I think that it is good to make the behavior stable if users use the default template with two http servers or they indeed need two http servers.

Just use your idea to separate the two http servers' status should do the work.
```
*startedUnixHttpServer uint32
*startedInetHttpServer uint32
...
and then CAS
```

**Comment by ochinchina** [comment]
@wxiaoguang it is fixed, please try

**Comment by wxiaoguang** [comment]
Thanks, seems pretty good. 👍
