### ISSUE TITLE
`go get`error

### ISSUE THREAD

**Issue by opriz** [ochinchina/supervisord#193]
When I use `go get` directly, it occurs module name error:
```
➜  ~ go get -u github.com/ochinchina/supervisord
go: extracting github.com/ochinchina/supervisord v0.6.7
go get: github.com/ochinchina/supervisord@v0.6.7: parsing go.mod:
	module declares its path as: supervisord
	        but was required as: github.com/ochinchina/supervisord
```
In current go.mod:
```
module supervisord
...
replace github.com/ochinchina/supervisord => ./
```
The module name is `supervisord` , but in other go source files, they refer to `github.com/ochinchina/supervisord`.By using 'replace' it works well when been built locally, but `go get` may treate `github.com/ochinchina/supervisord` as a dependency and try to get it on github, with the module named `github.com/ochinchina/supervisord` , but it just find module `supervisord`, so error occurs.
I think we can just change the module name `supervisord` to `github.com/ochinchina/supervisord`.I cannot verify this in my forked repo.

**Comment by ochinchina** [comment]
what is the version of your golang? and what operating system is used?

**Comment by opriz** [comment]
> what is the version of your golang? and what operating system is used?

my `go version` is:
`go version go1.13.1 darwin/amd64`
