### ISSUE TITLE
Releases 中只有linux编译版本，为什么没有windows编译版本啊？

### ISSUE THREAD

**Issue by yswang0927** [ochinchina/supervisord#199]
您好，好不容易找到了 Supervisor 的 windows版，但是在 Release中只看到了 Linux 的编译版本，没有看到 windows (7或10)的编译版本。

我对go-lang语言不懂，但是按照网上的教程在 windows7 下安装了 go-lang最新版，cmd > go version 显示 1.14.2 windows/amd64 ，go安装成功了，然后我下载了源码 source-0.6.3.zip 进行自己编译，我进入源码目录，执行 go build，结果报错：cannot find package "github.com/GeertJohan/go.rice" 等错误，不知道为什么？

**Comment by yswang0927** [comment]
自己在windows上编译搞定了，呵呵。

**Comment by yudidi** [comment]
> 自己在windows上编译搞定了，呵呵。
怎么编译的呢大佬

**Comment by yudidi** [comment]
> 自己在windows上编译搞定了，呵呵。

大佬怎么编译的呢？
