### ISSUE TITLE
能支持动态启动一个新进程任务吗？

### ISSUE THREAD

**Issue by yswang0927** [ochinchina/supervisord#200]
目前我的用法是：新增一个进程配置文件，然后执行 reload 方式进行新进程启动。
有没有更好的方式去启动一个指定的进程任务？

**Comment by ochinchina** [comment]
Currently we can only add a new program to the configuration file and reload the configuration file to start the program.

Maybe I will consider to provide an API to add a new program and start it.

**Comment by yswang0927** [comment]
期待下个版本能增加这个功能，这样使用起来就更灵活方便了，谢谢。
