### ISSUE TITLE
How to install it as system service?

### ISSUE THREAD

**Issue by ljet2165** [ochinchina/supervisord#214]
As we known, when we registed supervisor as system service, it will load all the *.ini of one sub directory,
So how to do the similar thing in this project?

BTW, excellent work!

**Comment by ochinchina** [comment]
What Operating system is used for the supervisor?

**Comment by ochinchina** [comment]
the supervisor can be running as a system service in linux with systemd. The supervisor.service is defined as:

```init
[Unit]
Description=Supervisord daemon

[Service]
Type=notify
ExecStart=/usr/bin/supervisord -d -c /etc/supervisor.conf
ExecStop=/usr/bin/supervisord ctl shutdown
ExecReload=/usr/bin/supervisord ctl reload
KillMode=process
Restart=on-failure
TimeoutStartSec=0
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

**Comment by kolkov** [comment]
Thanks! And for Gentoo + OperRC please!
