### ISSUE TITLE
Create a stable tag/release post 0.6.7

### ISSUE THREAD

**Issue by prashanthjbabu** [ochinchina/supervisord#217]
Hi @ochinchina ,
     The last tag that has been published is v0.6.7 , but this tag does not contain the fix for https://github.com/ochinchina/supervisord/commit/d4a1a6f1a26290c32d1a82e74420176d92868b48 which is a very core feature which breaks stopping of programs . 
    This makes v0.6.7 a broken release as a very basic feature is broken . Is it possible for you to create a new tag which is more stable which has this fix? Its preferred not to take code from master since it is ever changing.

**Comment by ochinchina** [comment]
v0.6.8 is released
