### ISSUE TITLE
pidproxy does not seems to kill all child processes

### ISSUE THREAD

**Issue by sandeepkalra** [ochinchina/supervisord#221]
I use patroni (postgres cluster management) that in turn starts postgres. When i say "supervisord ctl stop patrno" then patroni stops but not postgres. I am using pidproxy for patroni because It is spawned as child of patroni.

**Comment by ochinchina** [comment]
can you paste your supervisor configuration file in here? and then I can find the root-cause

**Comment by sandeepkalra** [comment]
I got the issue resolved. Marking this fixed.
