### ISSUE TITLE
启动过程报错，最后能启动成功

### ISSUE THREAD

**Issue by litliq** [ochinchina/supervisord#226]
你好，我现在遇到一个问题，想请教下是什么原因造成的

启动过程中，一直报错，"program stopped with status:signal: killed"，但是最后都能启动成功，为啥启动过程中会一直收到killed信号呢？

time="2020-10-10T18:21:02+08:00" level=info msg="program stopped with status:signal: killed" program=SearchEngineMainProgram
time="2020-10-10T18:21:02+08:00" level=info msg="################### Log Set OK: SearchEngineMainProgram"
time="2020-10-10T18:21:03+08:00" level=info msg="program stopped with status:signal: killed" program=SearchEngineMainProgram
time="2020-10-10T18:21:03+08:00" level=error msg="fail to start program because retry times is greater than 3" program=SearchEngineMainProgram
time="2020-10-10T18:21:03+08:00" level=info msg="################### Log Set OK: SearchEngineMainProgram"
time="2020-10-10T18:21:03+08:00" level=info msg="program stopped with status:signal: killed" program=SearchEngineMainProgram
time="2020-10-10T18:21:03+08:00" level=info msg="################### Log Set OK: SearchEngineMainProgram"
time="2020-10-10T18:21:04+08:00" level=info msg="program stopped with status:signal: killed" program=SearchEngineMainProgram
time="2020-10-10T18:21:04+08:00" level=info msg="################### Log Set OK: SearchEngineMainProgram"
time="2020-10-10T18:21:05+08:00" level=info msg="success to start program" program=SearchEngineMainProgram

**Comment by litliq** [comment]
我看了下SearchEngineMainProgram这个程序，确实是要初始化很久，初始化完成后，supervisord才显示状态Running，但是在初始化过程中，不应该一直收到killed信号才对，应该状态是Starting才对，有点茫然

**Comment by ochinchina** [comment]
把程序的startsecs参数设置长些（缺省是1秒），比如60，相关的描述：

startsecs

    The total number of seconds which the program needs to stay running after a startup to consider the start successful (moving the process from the STARTING state to the RUNNING state). Set to 0 to indicate that the program needn’t stay running for any particular amount of time.

    Note

    Even if a process exits with an “expected” exit code (see exitcodes), the start will still be considered a failure if the process exits quicker than startsecs.

    Default: 1

    Required: No.

    Introduced: 3.0

**Comment by litliq** [comment]
Thanks
