### ISSUE TITLE
config to achieve continous restart if failed

### ISSUE THREAD

**Issue by mmmint** [ochinchina/supervisord#23]
I have an app which should be monitored and always restarted in case of exit or failure (also if it keeps exiting). What I want to avoid is supervisord to stop restarting the app after some retries, but I doesnt work...
This is the tail of the output of supervisord:

`time="2017-07-02T10:58:50Z" level=info msg="Don't start the stopped program because its retry times 3 is greater than start retries 3" program=recorder
`
<br>
**supervisord.conf**:

```
[program:recorder]
command=/usr/sbin/recorder
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/recorder.log

```
With this config the superviord still stops trying after some cycles. Why?

**Comment by ochinchina** [comment]
the times of restarting for a program is controlled by parameter "startretries", its default value is 3 from the supervisord configuration document.

So if you want to start it for ever, you can set the "startretries" to a very big value such as 99999999.

**Comment by mmmint** [comment]
Its a shame such an application has no forever parameter for startretries...
