### ISSUE TITLE
非常感谢开发go版本的supervisord,能否和Python版的在网页控制台那里增加日志查看呢?

### ISSUE THREAD

**Issue by Jack2222-luck** [ochinchina/supervisord#257]
非常感谢开发go版本的supervisord,能否和Python版的在网页控制台那里增加日志查看呢?

这个功能非常适用,有的时候登录服务器太麻烦了,如果能在网页控制台查看当前程序的输出日志就很方便了.

Python版本的是有这个功能,希望也能增加进去.

再次感谢作者的开源精神

**Comment by cupen** [comment]
我个人以为网页控制台太臃肿了，不是 supervisord 该干的，提供 api 给你去定制会更合适。
关于登录服务器太麻烦的问题，这个很容易解决。
1. 配置好你的 $HOME/.ssh/config
2. ssh xx supervisord tail process-name
    完成。用 make 或其它 task 工具可进一步简化，比如 make watch-xxx 是不是更简单？

**Comment by ochinchina** [comment]
currently you can get the log by "supervisord ctl logtail <program-name>"

**Comment by Jack2222-luck** [comment]
学习了，py版本的日志也不是很完善，有的时候也经常无法输出。
