### ISSUE TITLE
supervisor v0.6.9 ctl status, 不同状态的服务显示都变成了黄色，更换显示颜色，是有什么特殊意义吗？

### ISSUE THREAD

**Issue by faith2god** [ochinchina/supervisord#260]
![image](https://user-images.githubusercontent.com/16483557/115807725-bef91800-a41b-11eb-9e88-946d94fa5498.png)
不同状态的服务都显示一个颜色，不太好区分

**Comment by ochinchina** [comment]
This is a bug for the different status with different color, and now it is fixed

**Comment by faith2god** [comment]
Yeap, it's fixed now
