### ISSUE TITLE
Win10下注册系统服务失败的问题

### ISSUE THREAD

**Issue by qingwenjie** [ochinchina/supervisord#264]
管理员权限下执行命令：.\supervisord.exe service install -c C:\supervisord\supervisor.conf

服务信息：
可执行文件路径：C:\supervisord\supervisord.exe --configuration=C:\supervisord\supervisor.conf

C:\supervisord\supervisor.conf 配置文件的内容：
[inet_http_server]
port = :9001

启动服务后报：
Windows 无法启动 go-supervisord 服务(位于 本地计算机 上)。
错误 1053: 服务没有及时响应启动或控制请求。

**Comment by qingwenjie** [comment]
已经解决，
失败原因：它在作为启动服务的时候在某些项列中可能需要设置相应的参数或数值才能够使它能够以一个系统服务来正常的被启动，所以导致它在作为服务启动的时候没有获得相应的结果

需要通过service.Run启动。

**Comment by XieGP** [comment]
> 已经解决，失败原因：它在作为启动服务的时候在某些项列中可能需要设置相应的参数或数值才能够使它能够以一个系统服务来正常的被启动，所以导致它在作为服务启动的时候没有获得相应的结果
> 通过service.Run启动即可。

可以请教下是如何解决的吗, 我尝试在service.go中吧s.Start()改成s.Run()并没有解决问题

**Comment by jaty613** [comment]
@qingwenjie 能贴出来具体解决的方式吗

**Comment by qingwenjie** [comment]
> > 已经解决，失败原因：它在作为启动服务的时候在某些项列中可能需要设置相应的参数或数值才能够使它能够以一个系统服务来正常的被启动，所以导致它在作为服务启动的时候没有获得相应的结果
> > 通过service.Run启动即可。
> 
> 可以请教下是如何解决的吗, 我尝试在service.go中吧s.Start()改成s.Run()并没有解决问题

把-c参数部分去掉就可以了，可以尝试由程序自动查找

**Comment by devops-fj** [comment]
@qingwenjie  可以给个具体 解决方法 我这边现在也解决不了
