### ISSUE TITLE
Under the arm board, the program cannot output the log

### ISSUE THREAD

**Issue by Hanker-13** [ochinchina/supervisord#288]
Hello, I have a problem. When my program is directly executed, I can see the log. After using supervisor management, there is only FMT output in the file, but I can't get the log output。
This is my system information：
`Linux am335x 3.2.0 #595 Wed Jan 31 00:13:29 PST 2018 armv7l GNU/Linux`

**Comment by Hanker-13** [comment]
There is no problem on other systems, only on this arm board. The log in my program uses `github.com/sirupsen/logrus`

**Comment by ochinchina** [comment]
if the github.com/sirupsen/logrus works in armv71, it should output the log normally.

Can you confirm github.com/sirupsen/logrus can't work in armv71?

**Comment by Hanker-13** [comment]
It should be the problem of `github.com/sirupsen/logrus`. If I change the package to `github.com/astaxie/beego/logs`, it will be OK.
