### ISSUE TITLE
Choose a different name to avoid confusion

### ISSUE THREAD

**Issue by mnaberez** [ochinchina/supervisord#30]
Please choose another name for this project.  The name `supervisord` is already used by similar project since 2004.  By giving this project the exact same name, it creates confusion.  

This will be especially true if a system ends up having both the Python package installed and this one.  The user may not realize which program is run.

**Comment by ochinchina** [comment]
Maybe change the binary name to go-supervisord

**Comment by mnaberez** [comment]
> Maybe change the binary name to go-supervisord

I think to avoid confusion, a new name for this project should be chosen that does not include `supervisord` at all.  There is already a well-known program called `supervisord`.  This is not that program.

**Comment by rcarmo** [comment]
I don't see any reason for this to be confusing. The README clearly states that this is inspired in `supervisord`, and I particularly like the fact that it uses the same naming conventions and config files. Until this becomes packaged into a Linux distro, I see zero chances of this being confusing to anyone who actually reads the docs.

**Comment by mnaberez** [comment]
> I particularly like the fact that it uses the same naming conventions and config files

It doesn't, which is part of the confusion.  This Go program does not support all the configuration options of `supervisord` so many valid `supervisord` configurations will not run (e.g. the plugin system is not supported at all).  To add to the confusion, this Go program has also diverged from `supervisord` and added it own unique configuration options that aren't present in `supervisord`, so configurations written for this program won't work on `supervisord`.

**Comment by mnaberez** [comment]
Since the author of Python `supervisord` is [promoting](https://twitter.com/chrismcdonough/status/931353842679136256) this Go package, I will close this issue.
