### ISSUE TITLE
Windows10 & Windows Server 注册系统服务均出现启动1053 错误

### ISSUE THREAD

**Issue by jaty613** [ochinchina/supervisord#311]
supervisord.exe service install -c '绝对路径配置文件'

**Comment by jaty613** [comment]
在service.go中提供获取当前服务的函数，在main.go的main函数中获取服务，同时调用服务实例的Run函数，将main中原来的runServer相关的调用移动到service.go中的run函数中

**Comment by pifeifei** [comment]
我也遇到相同问题了

supervisord.exe -d -c 'D:\lvse\supervisor\supervisord.conf'  is ok

`sc start go-supervisord`  提示  [SC] StartService 失败 1053:

**Comment by JieanYang** [comment]
> 我也遇到相同问题了
> 
> supervisord.exe -d -c 'D:\lvse\supervisor\supervisord.conf' is ok
> 
> `sc start go-supervisord` 提示 [SC] StartService 失败 1053:

![pb sc](https://user-images.githubusercontent.com/36827645/210178280-907fac2e-19bd-454a-9ca6-efed6374a3c4.png)
我遇到跟你相同的问题，你有找到解决办法吗？
通过 terminal 本地手动能够运行，通过service管理器启动提示。

我一直在想是不是因为http web程序阻塞导致 windows service 没法收到启动完成的指令等...
尝试过类似设置依然不行:
```
# supervisord-windows.conf file
command=C:\\Windows\\System32\\cmd.exe /C start /b C:\\Users\\*\\Desktop\\work\\supervisord-research\\go_test_api\\go_test_api.exe
```

**Comment by devops-fj** [comment]
@JieanYang 您好這個問題解決 了嘛

**Comment by JieanYang** [comment]
这个库对 windows 的兼容度不是很好，主要是针对 linux 做的优化
