### ISSUE TITLE
代码没有一致性,没有同步逻辑, 进程管理逻辑很烂

### ISSUE THREAD

**Issue by imkos** [ochinchina/supervisord#330]
1. 大量使用time.After 进行强等, 为什么不使用chan进行事件变动通知. 
2. 进程对象大量的锁使用, 为什么不使用CAS. 一些根本不用锁逻辑, 加了锁, 烂用

**Comment by labulakalia** [comment]
不满意就fork改

**Comment by imkos** [comment]
isRunning() 这个也是一个大坑

**Comment by dxgzg** [comment]
> 不满意就fork改

进程管理确实有问题，你看下就知道了，每一个进程用了两根gorotuine去管理，其实一根就够课的

**Comment by ochinchina** [comment]
Can you guys provide more detailed information?

**Comment by imkos** [comment]
[process.zip](https://github.com/ochinchina/supervisord/files/9399158/process.zip)
Refactored.

**Comment by yswang0927** [comment]
> 1. 大量使用time.After 进行强等, 为什么不使用chan进行事件变动通知.
> 2. 进程对象大量的锁使用, 为什么不使用CAS. 一些根本不用锁逻辑, 加了锁, 烂用

没有必要这样，大牛可以参与提交 PR，或许这样更能体现出大牛的技术能力。

**Comment by huapox** [comment]
发现问题可PR行动起来，不要只尖锐的点出问题 来github做喷子

你那么有本事的话，自己写一个放上来，把作者比下去撒
