### ISSUE TITLE
logtail Dead cycle

### ISSUE THREAD

**Issue by dxgzg** [ochinchina/supervisord#333]
use http or ctl get log,but not get it.When I debug,I find  func getLog() <-ch not have data.

supervisor.ini
[program:test]
directory = /XXX/XXXX/XXXX/test
command = ./test
stdout_logfile = /XXXX/XXXX/XXXXX/logs/console.log
stderr_logfile = /XXXXX/XXXXX/XXXX/logs/console.log

**Comment by ochinchina** [comment]
what command is used for tail the log? can you provide the detailed command?

**Comment by dxgzg** [comment]
> what command is used for tail the log? can you provide the detailed command?

./supervisord -c supervisor.ini start and use browser http:127.0.0.1:9996/logtail/test/stdout.It not view test logs.

**Comment by dxgzg** [comment]
> 

OK,Thank you
