### ISSUE TITLE
Pass complete environment to supervised processes

### ISSUE THREAD

**Issue by narcoticfresh** [ochinchina/supervisord#341]
Hi guys..

First of all, thanks for this project!

It seems that every supervised process starts with a "clean" environment (meaning it's environment variables) and each env has to be defined either by config or file..

Would it be possible to have a flag to just pass the entire environment that supervisord finds itself (meaning all defined environment variables) to its supervised processes? Like a setting "keep_environment=true" or something?

Especially in PHP apps (symfony with dotenv) there are many runtime ENVs that are needed (50+ variables) in our apps and to define these in supervisord config again is a failure risk (typos and such) and additional unnecessary work..

Would you consider this a possibility or would this be discouraged?

Thanks!

**Comment by ochinchina** [comment]
When starting the supervisord, the supervsisord will save all the available environment variables from its running environment. And when it starts an application, it will also pass all these environment variables to the application.

I believe when the supervisord is started, it can't get your desired environment variable.

**Comment by narcoticfresh** [comment]
closing as documented.. thanks @ochinchina
