### ISSUE TITLE
support for environment variables in configuration options

### ISSUE THREAD

**Issue by alxark** [ochinchina/supervisord#44]
Hello. Thank you for your project. I'm using go-supervisord for my docker container and it's really cool. I'm having a small feature request: i would like to use environment variables inside configuration options. I think i can create a PR but i would like to know your opinion about this feature first.

**Comment by ochinchina** [comment]
If you want to use the environment variable in the supervisor configuration file, this go-supervisord implementation already support it. Please refer the "Environment Variables" description in the supervisord document. I paste its description as below:

Environment Variables

Environment variables that are present in the environment at the time that supervisord is started can be used in the configuration file using the Python string expression syntax %(ENV_X)s:

[program:example]
command=/usr/bin/example --loglevel=%(ENV_LOGLEVEL)s

In the example above, the expression %(ENV_LOGLEVEL)s would be expanded to the value of the environment variable LOGLEVEL.

**Comment by alxark** [comment]
Thank you for your reply. Maybe it's better to update README.md with this information to make it more clear ?
