### ISSUE TITLE
stopwaitsecs没效果？

### ISSUE THREAD

**Issue by foxconndmd** [ochinchina/supervisord#47]
stopwaitsecs时间后程序没结束不发送kill强制终止？
配置：
[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=debug
pidfile=/tmp/supervisord.pid

[inet_http_server] 
port=127.0.0.1:9001

[program:test]
command=/root/test
autostart=true
autorestart=true
startsecs=2
startretries=3
stopwaitsecs=5
stopsignal=INT
stdout_logfile=/root/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
redirect_stderr=true

**Comment by ochinchina** [comment]
this issue is fixed and please try it

**Comment by foxconndmd** [comment]
谢谢，可以了。
