### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#49]
If you run a script that is not executable it will not start but you don't get a good error message.

**Comment by ochinchina** [comment]
any suggestion on the error message you want to get?

**Comment by Siecje** [comment]
Maybe capture the stdout from when the command was executed?

**Comment by ochinchina** [comment]
The stdout/stderr can be redirect to file with program configure item "stdout_logfile"/"stderr_logfile". Also you can redirect the program stdout/stderr to syslog.

**Comment by Siecje** [comment]
Okay there was no output, ,just a return code of `126`. Maybe that can be in the error message that says "fail to start program"? Ex "fail to start program: return code 126".

**Comment by ochinchina** [comment]
exit status is added in the log, please try it

**Comment by mmmint** [comment]
There is something which bothers me. When a program exits with an exception, while having redirected stdout_logfile or/and stderr_logfile, the program restarts as expected, but the log files are reinitialized instead of appending the content to it. This makes almost impossible to see what happens with the programs. Any hints on how to solve this?

**Comment by ochinchina** [comment]
now the log will be appended to the previous log file if it's max size does not exceed the limit.

**Comment by mmmint** [comment]
Thanks for your answer, but that doesn’t happen to me... They get truncated everytime the app restarts... Since when is this implemented (version)? How do you configure the max size limit?
Thanks in advance.

**Comment by ochinchina** [comment]
What is your "stdout_logfile"? it is in absolute path or relative path?

The max size is configured with parameter stdout_logfile_maxbytes/stderr_logfile_maxbytes. If this parameter is not configured, its default size is 50M.

**Comment by ochinchina** [comment]
Have you sync your source code to the latest?

**Comment by mmmint** [comment]
I tried, but now it can't even compile...and sadly go is not my primary language...
```
GOOS=linux GOARCH=arm go build github.com/ochinchina/supervisord
# github.com/ochinchina/supervisord
/home/user/go/src/github.com/ochinchina/supervisord/set_user_id.go:10: unknown field 'NoSetGroups' in struct literal of type syscall.Credential
```

**Comment by ochinchina** [comment]
Please use golang 1.9 to compile it

**Comment by mmmint** [comment]
Ok thanks, now it works! Had an old source...
Is there a way to get the version from supervisord? I really think its a nice feature to compare and know where you are...

**Comment by ochinchina** [comment]
it is a good idea for supervisor to print a version or build no. 
I will add a command line command to print the version later.
