### ISSUE TITLE
Custom stop logic

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#64]
Is it possible to have custom logic run instead of the default `supervisord ctl stop $program`?

Maybe add a config value which can be set to a script and that script is run when `stop` is called?

**Comment by ochinchina** [comment]
do you mean add a hook script for program in the supervisor if the program is stopped and the hook script will be called?

If you need a hook script, please write an event listener to listen the PROCESS_STATE event. For how to write event listener s

**Comment by Siecje** [comment]
I don't believe event types will help. 

It seems this has been a desired feature of the Python version for a while. https://github.com/Supervisor/supervisor/issues/147

Ideally when I stop a program instead of sending a signal I want to run a script and pass it the pid of the program process.

My exact use case is that I am using supervisord to run PostgreSQL. PostgreSQL will shutdown differently depending which signal you send it. https://www.postgresql.org/docs/10/static/server-shutdown.html

So the script would try sending `SIGTERM` and then after some time it would send `SIGINT` and then after some time it would send `SIGQUIT`.

I think I can still gracefully handle PostgreSQL shutdown by

1) Tell supervisord to not restart PostgreSQL (autorestart = false)
2) Get the pid of the process
2) Send signals to the process

Is it possible to set `autorestart = false` while supervisord is running and without editing the config file?

This go implementation doesn't have the ability to send signals to programs or to get the pid for a program process.

I couldn't find it in the Python supervisord docs but I found the command help text on StackOverflow.
```
signal <signal name> <name>     Signal a process
signal <signal name> <gname>:*      Signal all processes in a group
signal <signal name> <name> <name>  Signal multiple processes or groups
signal <signal name> all        Signal all processes
```
https://stackoverflow.com/a/13645290

Or should I do

1) supervisord ctl stop postgres
2) Wait...
And if it is still running (meaning the pid still exists?)
3) supervisord ctl signal INT postgres

**Comment by ochinchina** [comment]
signal sending in ctl is supported now

**Comment by ochinchina** [comment]
How is your PostgreSQL  daemon is managed by the supervisord? 
Have you used the pidproxy process or not? If the pidproxy is used, the pidproxy will forward the received signal to the PostgreSQL . So you can send a signal (one of SIGTERM, SIGINT or SIGQUIT) to the PostgreSQL .
If the current signal mechanism can't solve your problem, I will plan to implement "stop-command" in the [program:xxx] to stop program with your supplied script.

**Comment by Siecje** [comment]
Wow Thanks for adding the ability to send signals to programs 👍 

What is the pidproxy process?

My problem might not require a change to supervisord.

I want to send `SIGTERM` and then if Postgres is still not stopped then I want to send `SIGINT`.

If I have an open connection to Postgres it won't shutdown from `SIGTERM`, but it will from `SIGINT`.

If the `stopsignal` is set to `TERM` and I do

```shell
supervisord ctl stop postgres
```

That shell will hang and not return to the prompt. But also the process of the Postgres postmaster (top level postgres process) doesn't exist. There are processes run by the Postgres user that are owned by init (not supervisord). 

So I can't even send `SIGINT` to the process that supervisord sent `SIGTERM` because it doesn't exist anymore.

I find this behaviour very strange.

**Comment by ochinchina** [comment]
The supervisor requires program execute in block mode. A daemon program does not work in this way. Usually it writes its pid to a file and its main thread will exit. From the supervisor point view, it exits. 
In order to monitor this kind of daemon program, pidproxy ( you can go to the pidproxy directory to build it) program is designed. The pidproxy monitors the pid file of daemon application and check if the daemon application exit or not by sending signal 0 to that daemon application with the daemon pid.
Any signal sent to the pidproxy will be forward to the daemon application also.

I don't know if your Postgre runs in daemon mode or not. If it runs in daemon mode and its pid will be written to a file. Then you can wrap your Postgre with the pidproxy like below:

[postgre]

command = pidproxy <postgre-pid-file> <postgre-exeute-binay> <postgre-arg1> ... <postgre-argn>

**Comment by ochinchina** [comment]
Can the  new signal command satisfy your requirement?

**Comment by Siecje** [comment]
Okay I know what is happening.

Postgres will respond differently to different signals. [0]
- SIGTERM means don't accept new connections but wait until existing connections are closed.
- SIGINT will close existing connections and shutdown properly (without having to do a crash recovery (wal replay))

I want to send `SIGTERM` and then wait some amount of time and then send `SIGINT` to the top level postgres process (the postmaster).

This is what happens.
I have an open connection using `psql`, which prevents `SIGTERM` from stopping postgres because there is an active connection.
I have `stopsignal=TERM` in the supervisor config.

I tell supervisord to stop postgres
```shell
$ supervisord ctl stop postgres

```

And it doesn't return to the prompt until Postgres shuts down but it is not going to shutdown.

And then what is happening is that after 10 seconds supervisord is sending `SIGKILL` to Postgres and the child processes are re-parented to the `init` process. This is because the defaut value for `stopwaitsecs` is 10 seconds [1].

Sending SIGKILL to the Postgres postmaster is a bad idea. From the docs [0].

> It is best not to use SIGKILL to shut down the server. Doing so will prevent the server from releasing shared memory and semaphores, which might then have to be done manually before a new server can be started. Furthermore, SIGKILL kills the postgres process without letting it relay the signal to its subprocesses, so it will be necessary to kill the individual subprocesses by hand as well.

If I set `stopwaitsecs` to a large number then it will wait until the connection is closed.

Is it possible to set the signal to send after `stopwaitsecs`? Is it possible to disable `stopwaitsecs`?

0: https://www.postgresql.org/docs/10/static/server-shutdown.html
1: http://supervisord.org/configuration.html?highlight=stopwaitsecs

**Comment by Siecje** [comment]
Here is `htop` before and after `supervisord ctl postgres stop` and `stopwaitsecs`.

```
    1 root       20   0  9752  1924  1808 S  0.0  0.1  0:00.47 init
 1209 root       20   0 1335M 16576  6324 S  0.0  0.8 12:34.86 `- /boot/tp/bin/supervisord -c /boot/app/sysfiles/supervisord.conf -d
 1253 postgres   20   0  169M 16748 16120 S  0.0  0.9  1:03.42 |  `- /boot/tp/bin/postgres -D /boot/dd/db/
10389 postgres   20   0  170M  6564  5416 S  0.0  0.3  0:00.00 |  |  `- postgres: postgres dbname [local] idle
 1398 postgres   20   0  171M 10556  8816 S  0.0  0.5  1:45.22 |  |  `- postgres: dbname dbname 127.0.0.1(37520) idle
 1279 postgres   20   0 28056  3708  3012 S  0.0  0.2  2:49.86 |  |  `- postgres: stats collector process
 1278 postgres   20   0  170M  5888  4984 S  0.0  0.3  1:21.92 |  |  `- postgres: autovacuum launcher process
 1277 postgres   20   0  169M  8168  7504 S  0.0  0.4  0:50.13 |  |  `- postgres: wal writer process
 1276 postgres   20   0  169M  5108  4476 S  0.0  0.3  0:50.41 |  |  `- postgres: writer process
 1275 postgres   20   0  169M  6248  5564 S  0.0  0.3  0:01.77 |  |  `- postgres: checkpointer process
 1262 postgres   20   0 25796  2988  2372 S  0.0  0.2  0:00.00 |  |  `- postgres: logger process
```
 
After
 ```
    1 root       20   0  9752  1924  1808 S  0.0  0.1  0:00.47 init
10389 postgres   20   0  170M  6564  5416 S  0.0  0.3  0:00.00 `- postgres: postgres dbname [local] idle
 1398 postgres   20   0  171M 10556  8816 S  0.0  0.5  1:45.23 `- postgres: dbname dbname 127.0.0.1(37520) idle
 1262 postgres   20   0 25796  2988  2372 S  0.0  0.2  0:00.00 `- postgres: logger process
 1209 root       20   0 1335M 16576  6324 S  0.0  0.8 12:34.89 `- /boot/tp/bin/supervisord -c /boot/app/sysfiles/supervisord.conf -d
```

**Comment by Siecje** [comment]
Here is the code https://github.com/ochinchina/supervisord/blob/e5df21faf08876d43722931ead012ea095064516/process/process.go#L642-L659

What do you think about allowing `stopsignal` to be a list in addition to a single value?

On the stop call send the first signal in the list and then wait `stopwaitsecs` seconds and then send the next signal in the list and wait again. Then repeat until there are no more signals in the list.

**Comment by ochinchina** [comment]
it is a good idea to think the stopsignal as a list. I will try to implement this feature soon

**Comment by ochinchina** [comment]
stopsignal list is supported, please configure it as:

stopsignal = USR1 USR2

please try it

**Comment by Siecje** [comment]
@ochinchina Awesome it works great!

I am able to stop PostgreSQL properly and it works amazingly well.

This is my supervisord config

```
stopwaitsecs=60
stopsignal=TERM INT QUIT
```
