### ISSUE TITLE
eventlistener uses 100% CPU while listening

### ISSUE THREAD

**Issue by rwlincoln** [ochinchina/supervisord#74]
When an `eventlistener` is added `supervisord` uses 100% CPU even if all programs are idle. Take for example:

```ini
[program:a]
command = bash -c "sleep 8 && exit 2"

[eventlistener:a_exit]
command = ./event.sh
events=PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
```

where `event.sh` is:

```sh
#!/bin/sh
echo READY
read header
pkill supervisord
```

You should see this using 100% CPU for 8 seconds before it exits. Removing the `eventlistener` section solves the CPU issue, but `supervisord` doesn't exit.

**Comment by ochinchina** [comment]
the 100% CPU consumption for eventlistener is solved, please try again

**Comment by rwlincoln** [comment]
As you say, the changes made in 39d164213bca6025f46ae87c5e8232a9643834cf have solved this issue.
