### ISSUE TITLE
Add Docker Hub automated build for supervisord

### ISSUE THREAD

**Issue by rwlincoln** [ochinchina/supervisord#75]
May I suggest the addition of a `Dockerfile` and configuration of an automated build on [Docker Hub](https://hub.docker.com/). That way those wishing to add `supervisord` to a Docker image could simply do:

```Dockerfile
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord
```

Perhaps something along the lines of:

```Dockerfile
FROM golang:latest

ADD . /go/src/github.com/ochinchina/supervisord
RUN go build -o /usr/local/bin/supervisord github.com/ochinchina/supervisord

ENTRYPOINT ["supervisord"]
```

Once Docker Hub supports [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) more space efficient and Alpine based build could be added.

**Comment by Rbeuque74** [comment]
> Once Docker Hub supports multi-stage builds more space efficient and Alpine based build could be added.

Seems to be already the case ? https://github.com/docker/hub-feedback/issues/1039
