### ISSUE TITLE
Add automatised travis tests & deploy

### ISSUE THREAD

**Issue by Rbeuque74** [ochinchina/supervisord#80]
Hello,
Following #63 and #79, could you activate travis on the project to enable tests to be run when pull-requests are sent ?

This could be done on this URL: https://travis-ci.org/profile/ochinchina

Thanks!

**Comment by ochinchina** [comment]
I activate this project on the travis-ci, and successfully trigger a custom build.

**Comment by Rbeuque74** [comment]
Thanks !
