### ISSUE TITLE
Travis releases badly configured

### ISSUE THREAD

**Issue by rbeuque74** [ochinchina/supervisord#85]
Hello,
Seems like travis releases when a version is tagged is not working properly:

https://travis-ci.org/ochinchina/supervisord/builds/359690604#L686

**Comment by ochinchina** [comment]
seems the sort algorithm in the golang 1.10 is not a stable algorithm. And the golang 1.10.1 sort algorithm becomes stable algorithm again.

The order of program will not be compared if there is no dependency between them.

**Comment by Rbeuque74** [comment]
I was actually referring about the Travis configuration for release binaries
https://travis-ci.org/ochinchina/supervisord/builds/360621915#L685

release failed after 0.02s error=missing GITHUB_TOKEN

**Comment by ochinchina** [comment]
@Rbeuque74 How can we fix the GITHUB_TOKEN issue?

**Comment by Rbeuque74** [comment]
Hello @ochinchina ,
According to the goreleaser documentation, token have to be created on GitHub interface here: https://github.com/settings/tokens/new with the full repo permission.

Then, put the generated token to the Travis interface here: https://travis-ci.org/ochinchina/supervisord/settings in the "Environment Variables" section, key to GITHUB_TOKEN, as described here on the [Travis-CI documentation](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)

Source: [goreleaser documentation](https://goreleaser.com/#environment.git_hub_token)
