### ISSUE TITLE
Autostart 'unexpected' does not work correctly

### ISSUE THREAD

**Issue by Aisbergg** [ochinchina/supervisord#87]
**Expected:**
When using `autorestart=unexpected` the program is supposed to be restartet when the program exits with an exit code that is not one of the exit codes associated with this process’ configuration, as the official [documentation](http://supervisord.org/configuration.html) states it.

**Actual behaviour:**
The program will only be restarted when it exited correctly and not when it failed.

**Solution:**
The last condition needs to be negated, so that it becomes true if the exit code is not expected:
https://github.com/ochinchina/supervisord/blob/7b21d2c6d3606b633d71528eafd14bd19f599985/process/process.go#L295

**Comment by ochinchina** [comment]
change line:

return err == nil && p.inExitCodes(exitCode) 

to:

return err == nil && !p.inExitCodes(exitCode) 

to fix this issue

please try it

**Comment by Aisbergg** [comment]
fixed with #88
