### ISSUE TITLE
Feature: Extend SyslogLogger to support remote syslog daemons

### ISSUE THREAD

**Issue by Aisbergg** [ochinchina/supervisord#91]
A nice thing would be, if the logs could be send directly to a remote syslog server over UDP or TCP. This functionality is already implmented in the GO syslog package and could easily be implemented in supervisord.

**Proposal:**
The configuration file could be extended to supply protocol, host and port for the remote syslog server. Using the syntax of rsyslog the `X_logfile` variables could be adjusted like this:
```bash
# local syslog daemon
stdout_logfile=syslog
# remote syslog daemon over UDP
stdout_logfile=syslog @host:1234
# remote syslog daemon over TCP
stdout_logfile=syslog @@host:1234
```
And when a remote connection shall be opened the method [`syslog.Dial(...)`](https://golang.org/pkg/log/syslog/#Dial) can be called instead of `syslog.New(...)`

https://github.com/ochinchina/supervisord/blob/9991ad8a8bacd0fc57c34866099954afea48b1dd/logger/log_unix.go#L9-L15

**Comment by ochinchina** [comment]
the syslog is extened to support the remote syslog system now. To write log to remote syslog, we can configure it with "syslog @[protocol:]host[:port]" format. The protocol must be "tcp" or "udp". If protocol is missing, it's value is "udp". If port is missing, for udp/tcp protocol, it's value is 514/6514.

**Comment by Aisbergg** [comment]
Works like a charm :smiley: :thumbsup:
