### ISSUE TITLE
Multiple line values in configuration file

### ISSUE THREAD

**Issue by Siecje** [ochinchina/supervisord#96]
I tried to have a command that used multiple lines but this didn't work.
```
command=python myscript
    arg1 ; comment1
    arg2 ; comment2
```

This would work in the Python supervisord implementation[0][1]. 

It does work if you add a backslash to each line.
```
command=python myscript \
    arg1  \ ; comment1
    arg2    ; comment2
```

0: https://github.com/Supervisor/supervisor/issues/140
1: https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

**Comment by Siecje** [comment]
You can't have comments with the backslashes.

So this works
```
command=python myscript \
    arg1  \
    arg2
```

This does not work
```
command=python myscript \
    arg1  \ ; comment1
    arg2    ; comment2
```

**Comment by ochinchina** [comment]
@Siecje if you tested this fix or not?

**Comment by Siecje** [comment]
Yes this has been fixed.
